//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetZayav.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uze : DbContext
    {
        public uze()
            : base("name=uze")
        {
        }
        private static uze context;
        public static uze GetContext()
        {
            if (context == null)
                context = new uze();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Ispolnitel> Ispolnitel { get; set; }
        public virtual DbSet<Neisp> Neisp { get; set; }
        public virtual DbSet<Oborud> Oborud { get; set; }
        public virtual DbSet<Otchet> Otchet { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zapchast> Zapchast { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
